In [39]:
import numpy as np
import pandas as pd
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, LabelEncoder


newest_year = 2006

df = pd.read_csv('spreadspoke_scores.csv')
#encoding team names
encoder = OneHotEncoder(sparse_output=False)
encoded = encoder.fit_transform(df[['team_home', 'team_away']])
new_df = pd.DataFrame(encoded, columns=encoder.get_feature_names_out(['team_home', 'team_away']))

#dropping old data and games that haven't been played yet
df = pd.concat([df, new_df], axis=1).drop(df[df.score_home.isnull()].index).drop(df[df.schedule_season < newest_year].index)

#encoding true/false values
encoder = LabelEncoder()
df['stadium_neutral'] = encoder.fit_transform(df['stadium_neutral'])

#dropping columns that are not needed
# df['schedule_date'] = pd.to_datetime(df['schedule_date'], errors='coerce')
# df['year'] = df['schedule_date'].dt.year
df = df.drop(columns=['schedule_date', 'schedule_playoff', 'over_under_line', 'team_favorite_id', 'spread_favorite', 'stadium', 'weather_detail'])

#fixing missing values
df['weather_temperature'] = df['weather_temperature'].fillna(df['weather_temperature'].mean())
df['weather_wind_mph'] = df['weather_wind_mph'].fillna(df['weather_wind_mph'].mean())
df['weather_humidity'] = df['weather_humidity'].fillna(df['weather_humidity'].mean())

#Making sure week is a number
df['schedule_week'] = df['schedule_week'].replace(['Wildcard','Division', 'Conference', 'SuperBowl'], [18, 19, 20, 21])
df = df.reset_index(drop=True)

player_data = pd.read_csv('NFL_AllPlayers_Dataset.csv')

df = df.join(player_data.set_index(['season', 'week']), on=['schedule_season', 'schedule_week'], how='left')

df.to_csv('output.csv', index=False)
player_data

#.drop(columns=['team_home', 'team_away'])

,player_id,player_display_name,season,position,position_group,week,recent_team,completions,attempts,passing_yards,...,receiving_first_downs,receiving_epa,receiving_2pt_conversions,racr,target_share,air_yards_share,wopr,special_teams_tds,fantasy_points,fantasy_points_ppr
0,00-0000007,Rabih Abdullah,2003,RB,RB,12,CHI,0.00,0.00,0.00000,...,0.250000,-0.149513,0.0,0.000000,0.069770,0.000000,0.000000,0.0,0.766667,1.433333
1,00-0000007,Rabih Abdullah,2004,RB,RB,6,NE,0.00,0.00,0.00000,...,0.000000,-1.566050,0.0,0.000000,0.031947,0.000000,0.000000,0.0,1.366667,1.533333
2,00-0000100,Chidi Ahanotu,2004,DE,DL,1,MIA,0.00,0.00,0.00000,...,0.000000,-0.112252,0.0,0.000000,0.022727,0.000000,0.000000,0.0,0.000000,0.000000
3,00-0000108,David Akers,2002,K,SPEC,1,PHI,0.00,0.00,0.00000,...,0.000000,NaN,0.0,NaN,NaN,NaN,NaN,0.0,1.000000,1.000000
4,00-0000108,David Akers,2006,K,SPEC,1,PHI,1.00,1.00,11.00000,...,0.000000,NaN,0.0,NaN,NaN,NaN,NaN,0.0,0.440000,0.440000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12354,00-0038128,Malik Willis,2022,QB,QB,7,TEN,4.43,8.71,39.42857,...,0.000000,NaN,0.0,NaN,NaN,NaN,NaN,0.0,2.762857,2.762857
12355,00-0038129,Cade Otton,2022,TE,TE,15,TB,0.00,0.00,0.00000,...,1.533333,0.488437,0.0,1.246807,0.102576,0.082324,0.211491,0.0,3.793333,6.860000
12356,00-0038134,Kenneth Walker,2022,RB,RB,16,SEA,0.00,0.00,0.00000,...,0.375000,-0.876324,0.0,-2.171360,0.075727,-0.033347,0.090247,0.0,11.756250,13.506250
12357,00-0038147,Daylen Baldwin,2022,WR,WR,1,CLE,0.00,0.00,0.00000,...,2.000000,1.791362,0.0,1.000000,0.076923,0.223214,0.271635,0.0,2.500000,4.500000
12358,00-0038149,Josh Ali,2022,WR,WR,1,ATL,0.00,0.00,0.00000,...,0.000000,-0.519020,0.0,0.000000,0.035714,0.137615,0.149902,0.0,0.000000,0.000000