In [102]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import preprocessing
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

latest_year = 2015
enc = LabelEncoder()

df = pd.read_csv('spreadspoke_scores.csv')
df = df.drop(df[df.schedule_season < latest_year].index)

df_out = df.copy()
df_out = df.loc[:, df.columns.intersection(['score_home','score_away'])]
df = df.drop('score_home', axis=1)
df = df.drop('score_away', axis=1)
df['schedule_date'] = pd.to_datetime(df['schedule_date'], errors='coerce')
df['schedule_week'] = df['schedule_week'].replace(['Wildcard', 'Division', 'Conference', 'Superbowl'], 18)
df['day'] = df['schedule_date'].dt.day
df['month'] = df['schedule_date'].dt.month
df['year'] = df['schedule_date'].dt.year
df.drop(columns=['schedule_date'], inplace=True)
df['schedule_playoff'] = enc.fit_transform(df['schedule_playoff'])
df['team_home'] = enc.fit_transform(df['team_home'])
df['team_away'] = enc.fit_transform(df['team_away'])
df['team_favorite_id'] = enc.fit_transform(df['team_favorite_id'])
df['stadium'] = enc.fit_transform(df['stadium'])
df['stadium_neutral'] = enc.fit_transform(df['stadium_neutral'])
df['weather_humidity'] = enc.fit_transform(df['weather_humidity'])
df['weather_detail'] = enc.fit_transform(df['weather_detail'])
# df_teams = pd.read_csv('nfl_teams.csv')
# df_teams.drop(columns=['team_conference_pre2002', 'team_division_pre2002', 'team_name', 'team_name_short'], inplace=True)
# df_stadiums = pd.read_csv('nfl_stadiums.csv')
# df_stadiums.drop(columns=['stadium_location', 'stadium_open', 'stadium_close', 'stadium_address', 'stadium_weather_station_zipcode', 'stadium_weather_station', 'stadium_weather_station_name', 'stadium_latitude', 'stadium_longitude', 'stadium_azimuthangle'], inplace=True)
df_numpy = df.to_numpy()
X = preprocessing.scale(df_numpy)
y = df_out.to_numpy()
for i in range(len(y)):
    for j in range(len(y[i])):
        if np.isnan(y[i][j]):
            y[i][j] = 0
for i in range(len(X)):
    for j in range(len(X[i])):
        if np.isnan(X[i][j]):
            X[i][j] = 0
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [103]:
#df_teams
#df_stadiums
df

,schedule_season,schedule_week,schedule_playoff,team_home,team_away,team_favorite_id,spread_favorite,over_under_line,stadium,stadium_neutral,weather_temperature,weather_wind_mph,weather_humidity,weather_detail,day,month,year
11343,2015,1,0,21,27,33,-7.00,51,21,0,64.00,9.00,47,2,10,9,2015
11344,2015,1,0,0,22,2,-2.50,48.5,59,0,72.00,0.00,47,1,13,9,2015
11345,2015,1,0,3,13,23,-1.00,44.5,44,0,53.00,7.00,47,5,13,9,2015
11346,2015,1,0,5,11,18,-6.50,48.5,48,0,68.00,4.00,47,5,13,9,2015
11347,2015,1,0,8,23,12,-7.00,52.5,9,0,72.00,0.00,47,1,13,9,2015
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14068,2024,18,0,24,19,47,NaN,NaN,36,0,NaN,NaN,47,5,5,1,2025
14069,2024,18,0,26,23,47,NaN,NaN,28,0,NaN,NaN,47,5,5,1,2025
14070,2024,18,0,27,6,47,NaN,NaN,1,0,NaN,NaN,47,5,5,1,2025
14071,2024,18,0,32,22,47,NaN,NaN,45,0,NaN,NaN,47,5,5,1,2025
14072,2024,18,0,33,12,47,NaN,NaN,39,0,NaN,NaN,47,5,5,1,2025

In [96]:
from sklearn.datasets import make_regression
from sklearn.linear_model import LinearRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, r2_score


print(X.shape)
print(y.shape)

X_train, y_train = make_regression(n_samples=2730, n_features=17, n_informative=2, n_targets=2, random_state=1, noise=0.5)
model = LinearRegression()
model.fit(X_train, y_train)

yhat = model.predict(X_test)
print(yhat)
#print('R2: %.3f' % r2_score(y_test, yhat))

(2730, 17)
(2730, 2)
[[ 25.4232098    4.01032386]
 [ 45.35027302  52.01527686]
 [ 66.24417994  50.92904866]
 ...
 [ 66.19807861  50.86157854]
 [-98.00532989 -81.17558531]
 [ 35.1586295   40.26310499]]